export const REGISTER_USER = "REGISTER_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const SHOW_USER_NAME = "SHOW_USER_NAME";
export const GET_COURSES = "GET_COURSES";
export const GET_STUDENTS = "GET_STUDENTS";
export const DELETE_COURSE = "DELETE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const ADD_COURSE = "ADD_COURSE";
export const SET_COURSE_IMAGE ="SET_COURSE_IMAGE"
